server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://moviedb.cssmjcbtstkm.ap-southeast-2.rds.amazonaws.com:3306/MovieDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath:mappers/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


